
SELECT DISTINCT actorId, name
FROM Actors NATURAL JOIN PlaysIn NATURAL JOIN Movies M1
WHERE rating IS NOT NULL
GROUP BY actorId
HAVING NOT EXISTS
(
SELECT actorId
FROM Actors NATURAL JOIN PlaysIn NATURAL JOIN Movies M2
GROUP BY actorId
HAVING AVG(M2.rating) > AVG(M1.rating)
)
ORDER BY actorId
